server:
  port: 8080  # Server port for the Spring Boot app.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: MYsql@12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # Automatically updates the database schema (change to 'validate' for production)
    properties:
      hibernate:
        format_sql: true  # Formats SQL for readability