server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://yamanote.proxy.rlwy.net:57141/railway
    username: root
    password: HHmWrgEisqpdqahWpihQcewpOLspMGDM
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
